### ISSUE TITLE
A problem with self-signed SSL certificates

### ISSUE THREAD

**Issue by monolithed** [nodeca/navit#28]
``` js
let Navit = require('navit');

let browser = new Navit({
    engine : 'slimerjs',
    prefix : 'https://***.***.***.test.mail.ru'
}, {
    // 'ssl-protocol': 'tlsv1',
    // 'ignore-ssl-errors': 'yes'
    'debug': 'yes',
    // 'web-security': 'no',
});

browser
    .open('/user/delete')
    .run(error => {
        console.log('---', error);
        browser.close();
    })
;

```

I've some strange errors when I use options like`ignore-ssl-errors` or `web-security`:

```
[HeadlessError: Unexpected output from PhantomJS: --web-security not supported yet
```

```
[HeadlessError: Unexpected output from PhantomJS: --ignore-ssl-errors not supported yet
```

Without this options:

 `slimerjs`:

```
[HeadlessError: Unexpected output from PhantomJS: 2015-12-31T11:09:40.236Z [DEBUG] Gecko version: 33.1.1
2015-12-31T11:09:40.236Z [DEBUG] script args: /node_modules/node-phantom-simple/bridge.js
```

`phantomjs`: 

```
➜ export DEBUG=navit; /workspace/***/.nvm/versions/node/v5.3.0/bin/node apps/account/views/user/delete/tests/suite.js 
  navit do.open('https://***.***.***.test.mail.ru/user/delete') +0ms
/workspace/mail.ru/***/node_modules/navit/lib/do.js:152
    if (self.__response__.contentType.indexOf('text/html') === -1) {
                         ^

TypeError: Cannot read property 'contentType' of undefined
    at /workspace/mail.ru/***/node_modules/navit/lib/do.js:152:26
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:721:13
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:52:16
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:269:32
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:44:16
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:718:17
    at /workspace/mail.ru/***/node_modules/navit/node_modules/async/lib/async.js:167:37
    at /workspace/mail.ru/***/node_modules/navit/lib/do.js:142:9
    at /workspace/mail.ru/***/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/workspace/mail.ru/***/node_modules/node-phantom-simple/node-phantom-simple.js:641:9)
```

Also I've tried already `npm set strict-ssl false` it did not help me.
Any thoughts?

**Comment by puzrin** [comment]
https://github.com/laurentj/slimerjs/blob/master/API_COMPAT.md

slimerjs has some minor differences with phantomjs

**Comment by monolithed** [comment]
Does `slimerjs` not support `ignore-ssl-errors`?

**Comment by puzrin** [comment]
Yes. It does not supports it.

**Comment by monolithed** [comment]
Hm, I got it (

**Comment by puzrin** [comment]
Some features can be implemented differently (profiles instead of cookies_file), you need to read docs, i don't remember all details. In general, you can make work everyting that works in phantom.
